apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapplication1
  labels:
    app: testapplication1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testapplication1
  template:
    metadata:
      name: testapplication1
      labels:
        app: testapplication1
    spec:
      containers:
        - name: testapplication1
          image: aks2307/demodocker1:v0.1
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      